---
name: Workflow-Pipeline

on:
  push:
    branches:
      - main
      - development
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - 'docs/**'

jobs:
  code_quality:
    name: Code Quality🎖️
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:v1.59.1"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: GolangCI-Lint
        run: |
          golangci-lint run --timeout 9m0s

  linting_party:
    name: Linting Party🥳
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check for file names errors
        uses: ls-lint/action@v2.2.3
        with:
          config: .ls-lint.yml
